apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
data:
  NEXTCLOUD_UPDATE: "1"
  POSTGRES_HOST: postgres-service
  ALLOW_EMPTY_PASSWORD: "yes"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1"