apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app: nextcloud
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_USER: "ADMIN"
  NEXTCLOUD_ADMIN_PASSWORD: "ADMIN_PASSWORD"